Repository woowacourse-teams/2021-gpu-is-mine, pull requests merged in 2021-08, with the labels that each got.

#242 feat: 대기 중인 job 취소 기능 추가
  front-end/src/__fixtures__/gpuServersResponses.ts
  front-end/src/domains/GpuServerSelectItem/GpuServerSelectItem.tsx
  front-end/src/domains/JobInfoItem/JobInfoItem.tsx
  front-end/src/domains/JobInfoList/JobInfoList.tsx
  front-end/src/hooks/useApi/useApi.ts
  front-end/src/hooks/useHistory/useHistory.ts
  front-end/src/types/gpuServer.ts
Labels: FE

#248 refactor: Update 정책 변경
  back-end/src/main/java/mine/is/gpu/gpuserver/application/GpuServerService.java
  back-end/src/main/java/mine/is/gpu/gpuserver/domain/GpuBoard.java
  back-end/src/main/java/mine/is/gpu/gpuserver/domain/GpuServer.java
  back-end/src/main/java/mine/is/gpu/gpuserver/dto/request/GpuServerUpdateRequest.java
  back-end/src/main/java/mine/is/gpu/gpuserver/ui/GpuServerController.java
  back-end/src/main/java/mine/is/gpu/job/application/JobService.java
  back-end/src/main/java/mine/is/gpu/job/domain/Job.java
  back-end/src/main/java/mine/is/gpu/job/dto/request/JobUpdateRequest.java
  back-end/src/main/java/mine/is/gpu/job/ui/JobController.java
  back-end/src/main/java/mine/is/gpu/member/application/MemberService.java
  back-end/src/main/java/mine/is/gpu/member/dto/request/MemberInfoRequest.java
  back-end/src/main/java/mine/is/gpu/member/dto/request/MemberUpdateRequest.java
  back-end/src/main/java/mine/is/gpu/member/ui/MemberController.java
  back-end/src/test/java/mine/is/gpu/gpuserver/application/GpuServerServiceTest.java
  back-end/src/test/java/mine/is/gpu/gpuserver/fixture/GpuServerFixtures.java
  back-end/src/test/java/mine/is/gpu/gpuserver/ui/GpuServerAcceptanceTest.java
  back-end/src/test/java/mine/is/gpu/job/application/JobServiceTest.java
  back-end/src/test/java/mine/is/gpu/job/fixture/JobFixtures.java
  back-end/src/test/java/mine/is/gpu/job/ui/JobAcceptanceTest.java
  back-end/src/test/java/mine/is/gpu/member/application/MemberServiceTest.java
  back-end/src/test/java/mine/is/gpu/member/ui/MemberAcceptanceTest.java
Labels: BE

#254 fix: cache 전략을 제거한다
  front-end/src/__mocks__/handlers.ts
  front-end/src/constants/index.ts
  front-end/src/domains/JobDetail/JobDetail.test.tsx
  front-end/src/hooks/useApi/useApi.ts
  front-end/src/hooks/useAuth/useAuth.test.ts
  front-end/src/hooks/useFetch/useFetch.ts
  front-end/src/types/api.ts
  front-end/src/utils/axios.ts
Labels: 버그, FE

#256 feat: Job 상세조회 로그 새로고침 디자인을 개선한다
  front-end/src/components/Button/Button.styled.ts
  front-end/src/components/Text/Text.styled.ts
  front-end/src/components/Text/Text.tsx
  front-end/src/domains/JobDetail/JobDetail.styled.tsx
  front-end/src/domains/JobDetail/JobDetail.test.tsx
  front-end/src/domains/JobDetailLog/JobDetailLog.styled.tsx
  front-end/src/domains/JobDetailLog/JobDetailLog.tsx
  front-end/src/domains/JobDetailLogContent/JobDetailLogContent.tsx
  front-end/src/domains/JobDetailSummary/JobDetailSummary.test.tsx
  front-end/src/hooks/useFetch/useFetch.ts
Labels: FE

#252 test: useFetch 테스트 추가
  front-end/src/hooks/useFetch/useFetch.test.ts
  front-end/src/hooks/useFetch/useFetch.ts
Labels: FE

#255 feat: 중복 체크 기능 구현
  back-end/src/main/java/mine/is/gpu/exception/dto/ExceptionResponse.java
  back-end/src/main/java/mine/is/gpu/gpuserver/application/GpuServerService.java
  back-end/src/main/java/mine/is/gpu/gpuserver/domain/GpuServer.java
  back-end/src/main/java/mine/is/gpu/gpuserver/domain/repository/GpuServerRepository.java
  back-end/src/main/java/mine/is/gpu/gpuserver/dto/response/GpuBoardResponse.java
  back-end/src/main/java/mine/is/gpu/gpuserver/dto/response/GpuServerResponse.java
  back-end/src/main/java/mine/is/gpu/gpuserver/dto/response/GpuServerResponses.java
  back-end/src/main/java/mine/is/gpu/gpuserver/exception/GpuServerException.java
  back-end/src/main/java/mine/is/gpu/job/domain/repository/JobRepository.java
  back-end/src/main/java/mine/is/gpu/job/dto/request/JobRequest.java
  back-end/src/main/java/mine/is/gpu/job/dto/response/JobResponse.java
  back-end/src/main/java/mine/is/gpu/job/dto/response/JobResponses.java
  back-end/src/main/java/mine/is/gpu/lab/application/LabService.java
  back-end/src/main/java/mine/is/gpu/lab/domain/Lab.java
  back-end/src/main/java/mine/is/gpu/lab/domain/repository/LabRepository.java
  back-end/src/main/java/mine/is/gpu/lab/dto/LabResponse.java
  back-end/src/main/java/mine/is/gpu/lab/dto/LabResponses.java
  back-end/src/main/java/mine/is/gpu/lab/exception/LabException.java
  back-end/src/main/java/mine/is/gpu/mail/MailDto.java
  back-end/src/main/java/mine/is/gpu/member/application/MemberService.java
  back-end/src/main/java/mine/is/gpu/member/domain/Member.java
  back-end/src/main/java/mine/is/gpu/member/domain/repository/MemberRepository.java
  back-end/src/main/java/mine/is/gpu/member/dto/response/MemberResponse.java
  back-end/src/main/java/mine/is/gpu/member/exception/MemberException.java
  back-end/src/main/java/mine/is/gpu/worker/dto/LogsResponse.java
  back-end/src/test/java/mine/is/gpu/AcceptanceTest.java
  back-end/src/test/java/mine/is/gpu/auth/AuthAcceptanceTest.java
  back-end/src/test/java/mine/is/gpu/auth/ui/LoginInterceptorRegexTest.java
  back-end/src/test/java/mine/is/gpu/gpuserver/application/GpuServerServiceTest.java
  back-end/src/test/java/mine/is/gpu/gpuserver/domain/repository/GpuServerRepositoryTest.java
  back-end/src/test/java/mine/is/gpu/gpuserver/fixture/GpuServerFixtures.java
  back-end/src/test/java/mine/is/gpu/gpuserver/ui/GpuServerAcceptanceTest.java
  back-end/src/test/java/mine/is/gpu/gpuserver/ui/GpuServerControllerTest.java
  back-end/src/test/java/mine/is/gpu/job/application/JobServiceTest.java
  back-end/src/test/java/mine/is/gpu/job/domain/JobStatusTest.java
  back-end/src/test/java/mine/is/gpu/job/fixture/JobFixtures.java
  back-end/src/test/java/mine/is/gpu/job/ui/JobAcceptanceTest.java
  back-end/src/test/java/mine/is/gpu/job/ui/JobControllerTest.java
  back-end/src/test/java/mine/is/gpu/lab/application/LabServiceTest.java
  back-end/src/test/java/mine/is/gpu/lab/domain/repository/LabRepositoryTest.java
  back-end/src/test/java/mine/is/gpu/lab/ui/LabAcceptanceTest.java
  back-end/src/test/java/mine/is/gpu/mail/MailServiceTest.java
  back-end/src/test/java/mine/is/gpu/member/application/MemberServiceTest.java
  back-end/src/test/java/mine/is/gpu/member/domain/repository/MemberRepositoryTest.java
  back-end/src/test/java/mine/is/gpu/member/fixture/MemberFixtures.java
  back-end/src/test/java/mine/is/gpu/member/ui/MemberAcceptanceTest.java
  back-end/src/test/java/mine/is/gpu/worker/JobRepositoryTest.java
  back-end/src/test/java/mine/is/gpu/worker/application/WorkerServiceTest.java
  back-end/src/test/java/mine/is/gpu/worker/ui/WorkerAcceptanceTest.java
Labels: BE

#253 feat: flyway 도입
  back-end/build.gradle
  back-end/src/main/resources/application-dev.properties
  back-end/src/main/resources/application.properties
  back-end/src/main/resources/db/migration/V1__Initialize_project_tables.sql
  back-end/src/main/resources/logback-spring.xml
Labels: BE

#264 chore: cross-env를 사용해서 script 환경변수 설정
  front-end/package.json
  front-end/yarn.lock
Labels: 버그, 개선, FE

#281 refactor: test profile 추가
  back-end/src/main/java/mine/is/gpu/DataLoader.java
  back-end/src/main/resources/application-test.properties
  back-end/src/test/java/mine/is/gpu/AcceptanceTest.java
  back-end/src/test/java/mine/is/gpu/gpuserver/application/GpuServerServiceTest.java
  back-end/src/test/java/mine/is/gpu/gpuserver/domain/repository/GpuServerRepositoryTest.java
  back-end/src/test/java/mine/is/gpu/gpuserver/ui/GpuServerControllerTest.java
  back-end/src/test/java/mine/is/gpu/job/application/JobServiceTest.java
  back-end/src/test/java/mine/is/gpu/job/ui/JobControllerTest.java
  back-end/src/test/java/mine/is/gpu/lab/application/LabServiceTest.java
  back-end/src/test/java/mine/is/gpu/lab/domain/repository/LabRepositoryTest.java
  back-end/src/test/java/mine/is/gpu/member/application/MemberServiceTest.java
  back-end/src/test/java/mine/is/gpu/member/domain/repository/MemberRepositoryTest.java
  back-end/src/test/java/mine/is/gpu/worker/JobRepositoryTest.java
  back-end/src/test/java/mine/is/gpu/worker/application/WorkerServiceTest.java
Labels: BE

#275 chore: timezone setting
  back-end/auto-script-dev.sh
  back-end/auto-script-prod.sh
  back-end/src/main/java/mine/is/gpu/config/DefaultAppConfig.java
Labels: BE

#278 refactor : sonarqube의 제안에 따른 코드 스멜 정리
  back-end/src/main/java/mine/is/gpu/auth/infrastructure/AuthorizationExtractor.java
  back-end/src/main/java/mine/is/gpu/exception/http/CustomException.java
  back-end/src/main/java/mine/is/gpu/gpuserver/domain/GpuServer.java
  back-end/src/test/java/mine/is/gpu/AcceptanceTest.java
  back-end/src/test/java/mine/is/gpu/gpuserver/application/GpuServerServiceTest.java
  back-end/src/test/java/mine/is/gpu/gpuserver/domain/GpuBoardTest.java
  back-end/src/test/java/mine/is/gpu/gpuserver/domain/GpuServerTest.java
  back-end/src/test/java/mine/is/gpu/gpuserver/domain/repository/GpuServerRepositoryTest.java
  back-end/src/test/java/mine/is/gpu/job/domain/JobStatusTest.java
  back-end/src/test/java/mine/is/gpu/job/domain/JobTest.java
  back-end/src/test/java/mine/is/gpu/lab/application/LabServiceTest.java
  back-end/src/test/java/mine/is/gpu/lab/domain/LabTest.java
  back-end/src/test/java/mine/is/gpu/lab/domain/repository/LabRepositoryTest.java
  back-end/src/test/java/mine/is/gpu/member/application/MemberServiceTest.java
  back-end/src/test/java/mine/is/gpu/member/domain/repository/MemberRepositoryTest.java
  back-end/src/test/java/mine/is/gpu/worker/application/WorkerServiceTest.java
Labels: BE

#277 feat : cloudwatch application logging
  back-end/build.gradle
  back-end/src/main/java/mine/is/gpu/worker/ui/WorkerController.java
  back-end/src/main/resources/logback-spring.xml
  back-end/src/main/resources/logback.xml
Labels: BE

#294 feat: 예측 시간, 종료 시간을 Job에 추가, 예상 종료시간과 예상 시작시간을 응답으로 반환하도록 추가
  back-end/src/main/java/mine/is/gpu/job/domain/CalculatedTime.java
  back-end/src/main/java/mine/is/gpu/job/domain/Job.java
  back-end/src/main/java/mine/is/gpu/job/dto/request/JobRequest.java
  back-end/src/main/java/mine/is/gpu/job/dto/response/JobResponse.java
  back-end/src/main/java/mine/is/gpu/job/dto/response/JobResponses.java
  back-end/src/main/java/mine/is/gpu/worker/application/WorkerService.java
  back-end/src/main/resources/db/migration/V1__Initialize_project_tables.sql
  back-end/src/test/java/mine/is/gpu/job/application/JobServiceTest.java
  back-end/src/test/java/mine/is/gpu/job/ui/JobControllerTest.java
  back-end/src/test/java/mine/is/gpu/worker/application/WorkerServiceTest.java
Labels: BE

#296 feat: JobTable 컴포넌트 구현
  front-end/src/components/Table/Pagination.tsx
  front-end/src/components/Table/Table.stories.tsx
  front-end/src/components/Table/Table.styled.ts
  front-end/src/components/Table/Table.tsx
  front-end/src/components/Text/Text.tsx
  front-end/src/domains/Header/Header.tsx
  front-end/src/domains/Job.ts
  front-end/src/domains/JobTable/JobTable.stories.tsx
  front-end/src/domains/JobTable/JobTable.styled.ts
  front-end/src/domains/JobTable/JobTable.tsx
  front-end/src/hooks/index.ts
  front-end/src/hooks/usePagination/usePagination.ts
  front-end/src/types/jobs.ts
  front-end/src/types/table.ts
  front-end/src/utils/index.ts
  front-end/src/utils/object.ts
Labels: FE

#292 feat: Job 상세조회 페이지에 학습중인 Job 로그를 시각화한다
  front-end/.pnp.cjs
  front-end/.yarn/cache/@kurkle-color-npm-0.1.9-f688f703ac-511822c35a.zip
  front-end/.yarn/cache/@types-react-npm-17.0.16-3bb3803c27-cba60aeb28.zip
  front-end/.yarn/cache/chart.js-npm-3.5.0-66341440f6-9ce5400b3e.zip
  front-end/.yarn/cache/chartjs-plugin-zoom-npm-1.1.1-de179d890a-effd03bac9.zip
  front-end/.yarn/cache/compression-webpack-plugin-npm-8.0.1-ce23bcefc4-6290b8be8a.zip
  front-end/.yarn/cache/dequal-npm-2.0.2-370927eb6c-86c7a2c59f.zip
  front-end/.yarn/cache/hammerjs-npm-2.0.8-f656ba2573-b092da7d15.zip
  front-end/.yarn/cache/use-deep-compare-effect-npm-1.6.1-9b8915ea07-3724473628.zip
  front-end/package.json
  front-end/src/__fixtures__/jobsResponses.ts
  front-end/src/components/Button/Button.styled.ts
  front-end/src/components/Chart/Chart.stories.tsx
  front-end/src/components/Chart/Chart.tsx
  front-end/src/components/Chart/utils.ts
  front-end/src/components/index.ts
  front-end/src/domains/JobDetail/JobDetail.tsx
  front-end/src/domains/JobDetailGraph/JobDetailGraph.styled.tsx
  front-end/src/domains/JobDetailGraph/JobDetailGraph.tsx
  front-end/src/domains/JobDetailGraphChart/JobDetailGraphChart.stories.tsx
  front-end/src/domains/JobDetailGraphChart/JobDetailGraphChart.styled.ts
  front-end/src/domains/JobDetailGraphChart/JobDetailGraphChart.tsx
  front-end/src/domains/JobRegisterRadioGroup/JobRegisterRadioGroup.tsx
  front-end/src/domains/Manager.ts
  front-end/src/hooks/useApi/useApi.ts
  front-end/src/types/jobs.ts
  front-end/src/types/react.d.ts
  front-end/tsconfig.json
  front-end/webpack.config.js
  front-end/yarn.lock
Labels: FE

#318 chore: google webfont 적용
  front-end/src/styles/GlobalStyle.tsx
  front-end/src/styles/fonts/fonts.ts
  front-end/src/styles/fonts/noto-sans-kr/noto-sans-kr-v13-latin_korean-100.woff
  front-end/src/styles/fonts/noto-sans-kr/noto-sans-kr-v13-latin_korean-100.woff2
  front-end/src/styles/fonts/noto-sans-kr/noto-sans-kr-v13-latin_korean-300.woff
  front-end/src/styles/fonts/noto-sans-kr/noto-sans-kr-v13-latin_korean-300.woff2
  front-end/src/styles/fonts/noto-sans-kr/noto-sans-kr-v13-latin_korean-500.woff
  front-end/src/styles/fonts/noto-sans-kr/noto-sans-kr-v13-latin_korean-500.woff2
  front-end/src/styles/fonts/noto-sans-kr/noto-sans-kr-v13-latin_korean-700.woff
  front-end/src/styles/fonts/noto-sans-kr/noto-sans-kr-v13-latin_korean-700.woff2
  front-end/src/styles/fonts/noto-sans-kr/noto-sans-kr-v13-latin_korean-900.woff
  front-end/src/styles/fonts/noto-sans-kr/noto-sans-kr-v13-latin_korean-900.woff2
  front-end/src/styles/fonts/noto-sans-kr/noto-sans-kr-v13-latin_korean-regular.woff
  front-end/src/styles/fonts/noto-sans-kr/noto-sans-kr-v13-latin_korean-regular.woff2
Labels: 버그, FE

#319 fix: style 태그를 이용하여 google webfont import
  front-end/public/index.html
  front-end/src/styles/GlobalStyle.tsx
Labels: 버그, 긴급, FE

#261 GpuServer 상세조회 페이지를 구현한다
  front-end/src/__fixtures__/gpuServersResponses.ts
  front-end/src/__fixtures__/index.ts
  front-end/src/app/App.tsx
  front-end/src/components/Radio/Radio.stories.tsx
  front-end/src/components/Table/Table.styled.ts
  front-end/src/domains/GpuServer.ts
  front-end/src/domains/GpuServerDetail/GpuServerDetail.stories.tsx
  front-end/src/domains/GpuServerDetail/GpuServerDetail.styled.ts
  front-end/src/domains/GpuServerDetail/GpuServerDetail.tsx
  front-end/src/domains/GpuServerDetail/useGpuServerDetail.test.tsx
  front-end/src/domains/GpuServerDetail/useGpuServerDetail.ts
  front-end/src/domains/GpuServerDetailCurrentJob/GpuServerDetailCurrentJob.tsx
  front-end/src/domains/GpuServerDetailJobTable/GpuServerDetailJobTable.styled.ts
  front-end/src/domains/GpuServerDetailJobTable/GpuServerDetailJobTable.tsx
  front-end/src/domains/GpuServerDetailSummary/GpuServerDetailSummary.styled.ts
  front-end/src/domains/GpuServerDetailSummary/GpuServerDetailSummary.test.tsx
  front-end/src/domains/GpuServerDetailSummary/GpuServerDetailSummary.tsx
  front-end/src/domains/GpuServerDetailSummary/useGpuServerDetailSummary.ts
  front-end/src/domains/GpuServerInfoItem/GpuServerInfoItem.tsx
  front-end/src/domains/GpuServerInfoList/GpuServerInfoList.tsx
  front-end/src/domains/JobDetail/useJobDetail.ts
  front-end/src/domains/JobTable/JobTable.tsx
  front-end/src/hooks/useApi/useApi.ts
  front-end/src/hooks/useHistory/useHistory.ts
  front-end/src/pages/GpuServerViewDetail/GpuServerViewDetail.stories.tsx
  front-end/src/pages/GpuServerViewDetail/GpuServerViewDetail.tsx
  front-end/src/pages/index.ts
Labels: FE

#322 feat: Job 조회 시간 정보 실제 응답 값으로 변경
  front-end/src/__fixtures__/gpuServersResponses.ts
  front-end/src/__fixtures__/jobsResponses.ts
  front-end/src/domains/JobInfoItem/JobInfoItem.tsx
  front-end/src/domains/JobTable/JobTable.tsx
  front-end/src/domains/MemberSignupForm/MemberSignupForm.tsx
  front-end/src/types/jobs.ts
  front-end/src/utils/object.ts
Labels: FE

#321 feat: 학습중인 Job 로그 데이터의 자동갱신 기능을 구현한다
  front-end/src/constants/delay.ts
  front-end/src/constants/index.ts
  front-end/src/domains/GpuServerDetail/GpuServerDetail.tsx
  front-end/src/domains/GpuServerDetailCurrentJob/GpuServerDetailCurrentJob.tsx
  front-end/src/domains/JobDetail/JobDetail.tsx
  front-end/src/domains/JobDetail/useJobDetail.ts
  front-end/src/domains/JobDetailGraph/JobDetailGraph.stories.tsx
  front-end/src/domains/JobDetailGraph/JobDetailGraph.tsx
  front-end/src/domains/JobDetailLog/JobDetailLog.tsx
  front-end/src/hooks/index.ts
  front-end/src/hooks/useInterval/useInterval.ts
Labels: FE

#300 chore: production 모드에서 BASE_URL을 main server로 변경
  front-end/.pnp.cjs
  front-end/.yarn/cache/@types-node-npm-16.4.13-3f9c176458-071e86a1d1.zip
  front-end/package.json
  front-end/src/constants/api.ts
  front-end/src/domains/Header/Header.tsx
  front-end/webpack.config.js
  front-end/yarn.lock
Labels: FE
