Repository woowacourse-teams/2021-gpu-is-mine, pull requests merged in 2021-07, with the labels that each got.

#24 docs: 이슈 템플릿 셋팅
  .github/ISSUE_TEMPLATE/------------------.md
Labels: 환경설정

#28 docs: 이슈 템플릿 셋팅
  .github/ISSUE_TEMPLATE/------------------.md
Labels: 문서화

#31 feat: GPU 서버 현황 조회 페이지에 필요한 컴포넌트 구현
  front-end/.eslintrc.js
  front-end/.storybook/main.js
  front-end/.storybook/preview.js
  front-end/package.json
  front-end/src/App.tsx
  front-end/src/app/App.stories.tsx
  front-end/src/app/App.styled.ts
  front-end/src/app/App.tsx
  front-end/src/components/Button/Button.color.stories.tsx
  front-end/src/components/Button/Button.styled.ts
  front-end/src/components/Button/Button.tsx
  front-end/src/components/Flicker/Flicker.stories.tsx
  front-end/src/components/Flicker/Flicker.styled.ts
  front-end/src/components/Flicker/Flicker.tsx
  front-end/src/components/GpuIcon/GpuIcon.stories.tsx
  front-end/src/components/GpuIcon/GpuIcon.styled.ts
  front-end/src/components/GpuIcon/GpuIcon.tsx
  front-end/src/components/GpuIcon/gpu.svg
  front-end/src/components/ServerIcon/ServerIcon.stories.tsx
  front-end/src/components/ServerIcon/ServerIcon.styled.ts
  front-end/src/components/ServerIcon/ServerIcon.tsx
  front-end/src/components/ServerIcon/server.svg
  front-end/src/components/Text/Text.fontSize.stories.tsx
  front-end/src/components/Text/Text.fontWeight.stories.tsx
  front-end/src/components/Text/Text.styled.ts
  front-end/src/components/Text/Text.tsx
  front-end/src/components/VerticalBox/VerticalBox.stories.tsx
  front-end/src/components/VerticalBox/VerticalBox.styled.ts
  front-end/src/components/VerticalBox/VerticalBox.tsx
  front-end/src/index.tsx
  front-end/src/styles/GlobalStyle.tsx
  front-end/src/styles/colors.ts
  front-end/src/styles/fonts/fonts.styled.ts
  front-end/src/styles/fonts/noto-sans-kr/NotoSansKR-Black.woff2
  front-end/src/styles/fonts/noto-sans-kr/NotoSansKR-Bold.woff2
  front-end/src/styles/fonts/noto-sans-kr/NotoSansKR-Light.woff2
  front-end/src/styles/fonts/noto-sans-kr/NotoSansKR-Medium.woff2
  front-end/src/styles/fonts/noto-sans-kr/NotoSansKR-Regular.woff2
  front-end/src/styles/fonts/noto-sans-kr/NotoSansKR-Thin.woff2
  front-end/src/styles/fonts/noto-sans-kr/OFL.txt
  front-end/src/styles/reset.ts
  front-end/src/types/assets.d.ts
  front-end/src/types/util.ts
  front-end/tsconfig.json
  front-end/webpack.config.js
  front-end/yarn.lock
Labels: FE

#48 feat: viewports breakpoint 설정
  front-end/package.json
  front-end/src/styles/breakpoint.ts
  front-end/yarn.lock
Labels: FE

#92 feat: 페이지 라우팅 적용
  front-end/package.json
  front-end/src/app/App.styled.ts
  front-end/src/app/App.tsx
  front-end/src/constants/path.ts
  front-end/webpack.config.js
  front-end/yarn.lock
Labels: FE

#109 feat: GPU Server API를 뷰와 연결한다
  front-end/.eslintrc.js
  front-end/package.json
  front-end/src/components/Confirm/Confirm.stories.tsx
  front-end/src/components/Modal/Modal.stories.tsx
  front-end/src/components/Modal/Modal.tsx
  front-end/src/domains/GpuServerInfoItem/GpuServerInfoItem.stories.tsx
  front-end/src/domains/GpuServerInfoItem/GpuServerInfoItem.tsx
  front-end/src/domains/GpuServerRegisterForm/GpuServerRegisterForm.tsx
  front-end/src/fixtures/gpuServeViewrResponses.ts
  front-end/src/hooks/useFetch/useFetch.ts
  front-end/src/hooks/useForm/useForm.ts
  front-end/src/pages/manager/GpuServerView/GpuServerView.tsx
  front-end/src/styles/color.stories.tsx
  front-end/src/types/api.ts
  front-end/src/types/dialog.ts
  front-end/src/types/gpuServer.ts
  front-end/yarn.lock
Labels: FE

#123 fix: api url 변경
  front-end/src/constants/api.ts
Labels: 버그

#198 feat: accessToken 을 이용한 로그인 정책을 구현한다
  front-end/.storybook/preview.js
  front-end/src/app/App.tsx
  front-end/src/components/AuthProvider/AuthProvider.tsx
  front-end/src/components/AuthProvider/hooks.ts
  front-end/src/components/Layout/Layout.stories.tsx
  front-end/src/components/PrivateRoute/PrivateRoute.tsx
  front-end/src/components/PublicRoute/PublicRoute.tsx
  front-end/src/components/index.ts
  front-end/src/constants/path.ts
  front-end/src/domains/GpuServerInfoList/GpuServerInfoList.tsx
  front-end/src/domains/JobInfoList/JobInfoList.tsx
  front-end/src/domains/ManagerHeader/ManagerHeader.stories.tsx
  front-end/src/domains/ManagerHeader/ManagerHeader.tsx
  front-end/src/domains/ManagerNavigation/ManagerNavigation.styled.ts
  front-end/src/domains/ManagerNavigation/ManagerNavigation.test.tsx
  front-end/src/domains/ManagerNavigation/ManagerNavigation.tsx
  front-end/src/domains/ManagerSubHeader/ManagerSubHeader.stories.tsx
  front-end/src/domains/ManagerSubHeader/ManagerSubHeader.tsx
  front-end/src/domains/MemberLayout/MemberLayout.tsx
  front-end/src/domains/MemberLoginForm/MemberLoginForm.styled.ts
  front-end/src/domains/MemberLoginForm/MemberLoginForm.tsx
  front-end/src/domains/MemberSignupForm/MemberSignupForm.styled.ts
  front-end/src/domains/MemberSignupForm/MemberSignupForm.tsx
  front-end/src/hooks/index.ts
  front-end/src/hooks/useAuth/useAuth.test.ts
  front-end/src/hooks/useAuth/useAuth.ts
  front-end/src/hooks/useBoolean/useBoolean.ts
  front-end/src/pages/manager/GpuServerRegister/GpuServerRegister.tsx
  front-end/src/pages/manager/GpuServerView/GpuServerView.tsx
  front-end/src/pages/manager/JobRegister/JobRegister.tsx
  front-end/src/pages/manager/JobView/JobView.tsx
  front-end/src/pages/member/index.ts
  front-end/src/types/api.ts
  front-end/src/utils/string.ts
Labels: FE

#204 fix: job 등록 API url 변경
  front-end/src/__mocks__/handlers.ts
  front-end/src/constants/api.ts
  front-end/src/domains/JobRegisterForm/JobRegisterForm.tsx
  front-end/src/hooks/useAuth/useAuth.ts
Labels: 버그
