Repository woowacourse-teams/2021-gpu-is-mine, pull requests merged in 2021-10, with the labels that each got.

#403 feat: 마크업 구조를 개선한다.
  front-end/src/components/Layout/Layout.stories.tsx
  front-end/src/components/Layout/Layout.styled.ts
  front-end/src/components/Layout/Layout.tsx
  front-end/src/components/Text/Text.styled.ts
  front-end/src/components/Text/Text.tsx
  front-end/src/domains/GpuServerDetailJobTable/GpuServerDetailJobTable.tsx
  front-end/src/domains/GpuServerDetailSummary/GpuServerDetailSummary.styled.ts
  front-end/src/domains/GpuServerDetailSummary/GpuServerDetailSummary.tsx
  front-end/src/domains/GpuServerInfoItem/GpuServerInfoItem.styled.ts
  front-end/src/domains/GpuServerInfoList/GpuServerInfoList.styled.ts
  front-end/src/domains/Header/Header.tsx
  front-end/src/domains/JobDetailSummary/JobDetailSummary.styled.tsx
  front-end/src/domains/JobDetailSummary/JobDetailSummary.test.tsx
  front-end/src/domains/JobDetailSummary/JobDetailSummary.tsx
  front-end/src/domains/JobInfoItem/JobInfoItem.styled.ts
  front-end/src/domains/JobInfoList/JobInfoList.styled.ts
  front-end/src/domains/ManagerNavigation/ManagerNavigation.tsx
  front-end/src/domains/MemberLayout/MemberLayout.styled.ts
  front-end/src/domains/MemberLayout/MemberLayout.tsx
  front-end/src/domains/SubHeader/SubHeader.styled.ts
  front-end/src/domains/SubHeader/SubHeader.tsx
  front-end/src/domains/UserNavigation/UserNavigation.styled.ts
  front-end/src/domains/UserNavigation/UserNavigation.tsx
  front-end/src/hooks/index.ts
  front-end/src/hooks/usePathTitle/usePathTitle.ts
  front-end/src/pages/GpuServerRegister/GpuServerRegister.tsx
  front-end/src/pages/GpuServerView/GpuServerView.tsx
  front-end/src/pages/GpuServerViewDetail/GpuServerViewDetail.tsx
  front-end/src/pages/JobRegister/JobRegister.tsx
  front-end/src/pages/JobView/JobView.tsx
  front-end/src/pages/JobViewDetail/JobViewDetail.tsx
  front-end/src/pages/Login/Login.tsx
  front-end/src/pages/Signup/Signup.tsx
Labels: 개선, FE

#410 refactor: spring properties 파일을 정리
  back-end/src/main/resources/application-dev.properties
  back-end/src/main/resources/application-local.properties
  back-end/src/main/resources/application-prod.properties
  back-end/src/main/resources/application-test.properties
  back-end/src/main/resources/application-was1.properties
  back-end/src/main/resources/application-was2.properties
  back-end/src/main/resources/application.properties
  back-end/src/main/resources/application.yml
Labels: 개선, BE

#441 refactor: Alert, Confirm의 디자인을 변경한다
  front-end/.yarn/sdks/typescript/lib/tsserver.js
  front-end/.yarn/sdks/typescript/lib/tsserverlibrary.js
  front-end/cypress/integration/member/login.test.ts
  front-end/cypress/integration/member/signup.test.ts
  front-end/src/components/Alert/Alert.stories.tsx
  front-end/src/components/Alert/Alert.styled.ts
  front-end/src/components/Alert/Alert.tsx
  front-end/src/components/Button/Button.styled.ts
  front-end/src/components/Button/Button.tsx
  front-end/src/components/Confirm/Confirm.styled.ts
  front-end/src/components/Confirm/Confirm.tsx
  front-end/src/components/Dialog/Dialog.stories.tsx
  front-end/src/components/Dialog/Dialog.styled.ts
  front-end/src/components/Dialog/Dialog.tsx
  front-end/src/components/Dimmer/Dimmer.styled.ts
  front-end/src/components/Dimmer/Dimmer.tsx
  front-end/src/components/Modal/Modal.stories.tsx
  front-end/src/components/Modal/Modal.tsx
  front-end/src/components/ModalProvider/ModalProvider.tsx
  front-end/src/components/index.ts
  front-end/src/domains/GpuServerInfoItem/GpuServerInfoItem.test.tsx
  front-end/src/domains/GpuServerInfoItem/GpuServerInfoItem.tsx
  front-end/src/domains/GpuServerRegisterForm/GpuServerRegisterForm.tsx
  front-end/src/domains/JobDetail/JobDetail.test.tsx
  front-end/src/domains/JobDetail/JobDetail.tsx
  front-end/src/domains/JobInfoItem/JobInfoItem.tsx
  front-end/src/domains/JobRegisterForm/JobRegisterForm.tsx
  front-end/src/pages/Login/Login.test.tsx
  front-end/src/pages/Login/Login.tsx
  front-end/src/pages/Signup/Signup.test.tsx
  front-end/src/pages/Signup/Signup.tsx
  front-end/src/styles/colors.ts
  front-end/src/types/dialog.ts
  front-end/src/types/index.ts
Labels: 개선, FE

#425 feat: Service 계층의 Client, Storage 를 구현한다
  front-end/cypress/integration/member/signup.test.ts
  front-end/src/__mocks__/handlers.ts
  front-end/src/constants/api.ts
  front-end/src/constants/storageKey.ts
  front-end/src/features/member/authSlice.ts
  front-end/src/features/member/signupSlice.ts
  front-end/src/hooks/index.ts
  front-end/src/hooks/useAuthorize/useAuthorize.ts
  front-end/src/pages/Login/Login.test.tsx
  front-end/src/pages/Login/Login.tsx
  front-end/src/pages/Signup/Signup.tsx
  front-end/src/services/Storage.ts
  front-end/src/services/api/authApiClient.ts
  front-end/src/services/index.ts
  front-end/src/types/members.ts
  front-end/src/utils/axios.ts
Labels: FE
